apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine


---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: nginx-pod # Selects Pods with the label 'app: my-nginx'
  ports:
    - protocol: TCP
      port: 80       # The port other Pods use to access the Service
      targetPort: 80

